"""Accrual schedule generation."""

from __future__ import annotations

import re
from dataclasses import dataclass
from datetime import date
from typing import Literal

from dateutil.relativedelta import relativedelta

from .calendar_us import BusinessDayConvention, USCalendar

StubType = Literal["ShortFront", "ShortBack", "LongFront", "LongBack"]

_FREQ_RE = re.compile(r"^(\d+)([DWMY])$", re.IGNORECASE)


def parse_frequency(freq: str) -> relativedelta:
    """'1Y' -> 1 year, '6M' -> 6 months, '3M', '1W', '1D'."""
    m = _FREQ_RE.match(freq.strip())
    if not m:
        raise ValueError(f"Bad frequency string: {freq!r}; expected like '1Y', '6M', '1W', '1D'")
    n, unit = int(m.group(1)), m.group(2).upper()
    if unit == "Y":
        return relativedelta(years=n)
    if unit == "M":
        return relativedelta(months=n)
    if unit == "W":
        return relativedelta(weeks=n)
    return relativedelta(days=n)


@dataclass(frozen=True)
class AccrualPeriod:
    start: date
    end: date
    payment_date: date

    @property
    def days(self) -> int:
        return (self.end - self.start).days


def generate_schedule(
    effective_date: date,
    termination_date: date,
    frequency: str,
    calendar: USCalendar,
    business_day_convention: BusinessDayConvention = "ModifiedFollowing",
    stub: StubType = "ShortFront",
    payment_delay_bdays: int = 0,
    payment_calendar: USCalendar | None = None,
) -> list[AccrualPeriod]:
    """Generate accrual periods from `effective_date` to `termination_date`.

    Periods are generated by rolling backward from the termination date for
    `ShortFront` (short stub at the front, the swap-market default) or forward
    from the effective date for `ShortBack`.

    Period start/end dates are rolled by `business_day_convention` on `calendar`.
    Payment date = period end + `payment_delay_bdays` business days on
    `payment_calendar` (defaults to `calendar`).
    """
    if termination_date <= effective_date:
        raise ValueError(f"termination_date {termination_date} must be > effective_date {effective_date}")
    step = parse_frequency(frequency)
    pay_cal = payment_calendar or calendar

    unadjusted: list[date] = []
    if stub in ("ShortFront", "LongFront"):
        cur = termination_date
        while cur > effective_date:
            unadjusted.append(cur)
            cur = cur - step
        if stub == "LongFront" and unadjusted and unadjusted[-1] != effective_date:
            unadjusted = unadjusted[:-1]  # merge stub into prior period
        unadjusted.append(effective_date)
        unadjusted.reverse()
    else:  # ShortBack / LongBack
        cur = effective_date
        while cur < termination_date:
            unadjusted.append(cur)
            cur = cur + step
        if stub == "LongBack" and unadjusted and unadjusted[-1] != termination_date:
            unadjusted = unadjusted[:-1]
        unadjusted.append(termination_date)

    rolled = [calendar.roll(d, business_day_convention) for d in unadjusted]

    periods: list[AccrualPeriod] = []
    for s, e in zip(rolled[:-1], rolled[1:]):
        pay = pay_cal.add_business_days(e, payment_delay_bdays) if payment_delay_bdays else e
        periods.append(AccrualPeriod(start=s, end=e, payment_date=pay))
    return periods
